export interface MenuItem {
    id: string;
    name: string;
    description: string;
    price?: number;
    priceSmall?: number;
    priceLarge?: number;
    veg?: boolean;
    tags?: string[];
    category: string;
    subcategory?: string;
}

export interface MenuCategory {
    id: string;
    name: string;
    items: MenuItem[];
    subcategories?: string[];
}

export const menuData: MenuCategory[] = [
    {
        id: 'veg-pizzas',
        name: 'Vegetarian Pizzas',
        items: [
            {
                id: 'aromatica-veg',
                name: 'Aromatica',
                description: 'Pizza Sauce, Mozzarella Cheese, Zucchini, Olives, Mushrooms, Roasted Nuts, Leeks, Parsley, Herb oil',
                priceSmall: 359,
                priceLarge: 505,
                veg: true,
                category: 'pizzas',
                subcategory: 'veg',
            },
            {
                id: 'florentine',
                name: 'Florentine',
                description: 'Pizza Sauce, Spinach, Garlic onion confit, Feta, Parsley',
                priceSmall: 359,
                priceLarge: 505,
                veg: true,
                category: 'pizzas',
                subcategory: 'veg',
            },
            {
                id: 'veg-carnivores',
                name: 'Veg Carnivores',
                description: 'Pizza sauce, Tomato, Artichoke, Bell peppers, Black olive, onion, Corn, Nuts',
                priceSmall: 359,
                priceLarge: 505,
                veg: true,
                category: 'pizzas',
                subcategory: 'veg',
            },
            {
                id: 'fungi',
                name: 'Fungi',
                description: 'Pizza sauce, Mushroom, Jalapeno, Mozzarella, Black olive',
                priceSmall: 359,
                priceLarge: 505,
                veg: true,
                category: 'pizzas',
                subcategory: 'veg',
            },
            {
                id: 'amigo',
                name: 'Amigo',
                description: 'Pizza sauce, Mix bell peppers, Onion, Green chilli, Jalapeno, Corn, Mozzarella',
                priceSmall: 359,
                priceLarge: 505,
                veg: true,
                category: 'pizzas',
                subcategory: 'veg',
            },
            {
                id: 'paneer-tikka',
                name: 'Paneer Tikka',
                description: 'Pizza sauce, Paneer, Onion, Coriander, Capsicum, lime, mint sauce',
                priceSmall: 390,
                priceLarge: 596,
                veg: true,
                category: 'pizzas',
                subcategory: 'veg',
            },
            {
                id: 'pepperonata',
                name: 'Pepperonata',
                description: 'Pizza sauce, Mix peppers, Black Olives, Cherry tomato, Mozzarella',
                priceSmall: 462,
                priceLarge: 666,
                veg: true,
                category: 'pizzas',
                subcategory: 'veg',
            },
        ],
    },
    {
        id: 'non-veg-pizzas',
        name: 'Non-Vegetarian Pizzas',
        items: [
            {
                id: 'kerala-beef-fry',
                name: 'Kerala Beef Fry',
                description: 'Pizza Sauce, Beef keema, Curry leaf, Coconut, Onion, Mozzarella, Lime',
                priceSmall: 462,
                priceLarge: 666,
                veg: false,
                tags: ['fusion-hit'],
                category: 'pizzas',
                subcategory: 'non-veg',
            },
            {
                id: 'don-pollo',
                name: 'Don Pollo',
                description: 'Pizza Sauce, Mozzarella Cheese, Grilled Chicken, Pork Bacon, Mushroom, BBQ Sauce',
                priceSmall: 514,
                priceLarge: 720,
                veg: false,
                tags: ['bestseller'],
                category: 'pizzas',
                subcategory: 'non-veg',
            },
            {
                id: 'diavola',
                name: 'Diavola',
                description: 'Pizza Sauce, Mozzarella Cheese, Pork pepperoni, Fresh Chilly, Mushrooms, Black Olives, Oregano',
                priceSmall: 514,
                priceLarge: 720,
                veg: false,
                category: 'pizzas',
                subcategory: 'non-veg',
            },
            {
                id: 'woodkraft-meaty',
                name: 'Woodkraft Meaty',
                description: 'Pizza sauce, Pepperoni, Chorizo, Chicken, Onion, Mozzarella',
                priceSmall: 514,
                priceLarge: 720,
                veg: false,
                category: 'pizzas',
                subcategory: 'non-veg',
            },
            {
                id: 'mediterranean',
                name: 'Mediterranean',
                description: 'Pizza sauce, Chicken, Black Olive, Feta, Mozzarella, Onion, Bell peppers',
                priceSmall: 462,
                priceLarge: 666,
                veg: false,
                category: 'pizzas',
                subcategory: 'non-veg',
            },
            {
                id: 'bbq-chicken-hawaiian',
                name: 'BBQ Chicken Hawaiian',
                description: 'Pizza sauce, grilled chicken, BBQ sauce, Fresh Pineapple, Onion, Green chilli, Capsicum, Cilantro',
                priceSmall: 390,
                priceLarge: 596,
                veg: false,
                category: 'pizzas',
                subcategory: 'non-veg',
            },
            {
                id: 'chicken-tikka',
                name: 'Chicken Tikka',
                description: 'Pizza sauce, Chicken, Onion, Coriander, Capsicum, lime, Mint sauce',
                priceSmall: 390,
                priceLarge: 596,
                veg: false,
                category: 'pizzas',
                subcategory: 'non-veg',
            },
            {
                id: 'terra-e-mare',
                name: 'Terra E Mare',
                description: 'Pizza Sauce, Tuna, Onion, Mix peppers',
                priceSmall: 390,
                priceLarge: 596,
                veg: false,
                category: 'pizzas',
                subcategory: 'non-veg',
            },
            {
                id: 'pepperoni',
                name: 'Pepperoni',
                description: 'Pizza sauce, mozzarella cheese, Pork pepperoni, onion',
                priceSmall: 529,
                priceLarge: 742,
                veg: false,
                category: 'pizzas',
                subcategory: 'non-veg',
            },
            {
                id: 'arabic-keema',
                name: 'Arabic Keema',
                description: 'Pizza sauce, mozzarella cheese, bell peppers, onion, tomato, mutton keema, arabic spices, garlic sauce, parsley, lime',
                priceSmall: 529,
                priceLarge: 742,
                veg: false,
                category: 'pizzas',
                subcategory: 'non-veg',
            },
            {
                id: 'shrimp-pesto',
                name: 'Shrimp Pesto',
                description: 'Pesto sauce, mozzarella cheese, onion, green chilly, capers, olives, shrimp',
                priceSmall: 508,
                priceLarge: 720,
                veg: false,
                category: 'pizzas',
                subcategory: 'non-veg',
            },
            {
                id: 'chorizo',
                name: 'Chorizo',
                description: 'Pizza sauce, mozzarella cheese, onion, potato, Goan chorizo',
                priceSmall: 508,
                priceLarge: 720,
                veg: false,
                category: 'pizzas',
                subcategory: 'non-veg',
            },
        ],
    },
    {
        id: 'pasta',
        name: 'Pasta',
        items: [
            {
                id: 'aromatica-pasta',
                name: 'Aromatica Non-Veg Pasta',
                description: 'Pesto sauce, mix green veggies, chicken, capers, olives & cherry tomato with choice of penne or spaghetti',
                price: 381,
                veg: false,
                category: 'pasta',
            },
            {
                id: 'bolognese',
                name: 'Bolognese',
                description: 'Slow cooked meat sauce with choice of penne or spaghetti',
                price: 391,
                veg: false,
                category: 'pasta',
            },
            {
                id: 'lasagne',
                name: 'Lasagne',
                description: 'Classic Italian layered pasta with meat served with blend of tomato and alfredo sauce',
                price: 391,
                veg: false,
                category: 'pasta',
            },
        ],
    },
    {
        id: 'starters',
        name: 'Starters',
        items: [
            {
                id: 'calzone',
                name: 'Calzone',
                description: 'Filled with mixed herb butter, parsley, fresh garlic & shredded mozzarella cheese',
                price: 252,
                veg: true,
                category: 'starters',
            },
            {
                id: 'pizza-bomb',
                name: 'Pizza Bomb',
                description: 'Freshly baked pizza bites served with homemade tomato sauce',
                price: 185,
                veg: true,
                category: 'starters',
            },
            {
                id: 'chilli-cheddar-triangle',
                name: 'Chilli Cheddar Triangle',
                description: "Thin layer of pastry filled with cheddar cheese & Kerala's own kandhari chilli served with chilli lemon",
                price: 288,
                veg: true,
                category: 'starters',
            },
            {
                id: 'ricotta-spinach-triangle',
                name: 'Ricotta Spinach Triangle',
                description: 'Thin layer of pastry stuffed with ricotta cheese & spinach served with chilli lemon dip',
                price: 288,
                veg: true,
                category: 'starters',
            },
            {
                id: 'spicy-bbq-chicken-wing',
                name: 'Spicy BBQ Chicken Wing',
                description: 'Oven charred chicken wings glazed with house made spicy BBQ sauce',
                price: 304,
                veg: false,
                category: 'starters',
            },
            {
                id: 'mozzarella-sticks',
                name: 'Mozzarella Sticks',
                description: 'Crumb fried sticks of mozzarella served with house made Italian herb dip',
                price: 288,
                veg: true,
                category: 'starters',
            },
        ],
    },
    {
        id: 'mojitos',
        name: 'Mojitos',
        items: [
            {
                id: 'cucumber-basil',
                name: 'Cucumber Basil',
                description: 'Refreshing cucumber and basil mojito',
                price: 120,
                veg: true,
                category: 'drinks',
                subcategory: 'mojitos',
            },
            {
                id: 'green-apple-cucumber',
                name: 'Green Apple Cucumber',
                description: 'Green apple and cucumber mojito',
                price: 120,
                veg: true,
                category: 'drinks',
                subcategory: 'mojitos',
            },
            {
                id: 'litchi-mojito',
                name: 'Litchi Mojito',
                description: 'Sweet litchi flavored mojito',
                price: 120,
                veg: true,
                category: 'drinks',
                subcategory: 'mojitos',
            },
            {
                id: 'peach-lavender',
                name: 'Peach Lavender',
                description: 'Peach and lavender infused mojito',
                price: 120,
                veg: true,
                category: 'drinks',
                subcategory: 'mojitos',
            },
            {
                id: 'melon-lavender',
                name: 'Melon Lavender',
                description: 'Melon and lavender mojito',
                price: 120,
                veg: true,
                category: 'drinks',
                subcategory: 'mojitos',
            },
            {
                id: 'virgin-mojito',
                name: 'Virgin Mojito',
                description: 'Classic virgin mojito',
                price: 120,
                veg: true,
                category: 'drinks',
                subcategory: 'mojitos',
            },
        ],
    },
    {
        id: 'signature-drinks',
        name: 'Signature Drinks',
        items: [
            {
                id: 'lemon-ginger-nariyal',
                name: 'Lemon Ginger Nariyal Paani',
                description: 'Coconut flavour drink with lemon and ginger',
                price: 110,
                veg: true,
                category: 'drinks',
                subcategory: 'signature',
            },
            {
                id: 'jamun-kala-khata',
                name: 'Jamun Kala Khata',
                description: 'Jamun fruit with cumin and black salt',
                price: 110,
                veg: true,
                category: 'drinks',
                subcategory: 'signature',
            },
            {
                id: 'hibiscus-tea',
                name: 'Hibiscus Tea',
                description: 'Hibiscus flavour infused with tea',
                price: 110,
                veg: true,
                category: 'drinks',
                subcategory: 'signature',
            },
            {
                id: 'guava-chilli',
                name: 'Guava Chilli',
                description: 'Guava and chilli flavour drink',
                price: 110,
                veg: true,
                category: 'drinks',
                subcategory: 'signature',
            },
            {
                id: 'mint-mojito-drink',
                name: 'Mint Mojito',
                description: 'Mint and lemon flavour drink',
                price: 110,
                veg: true,
                category: 'drinks',
                subcategory: 'signature',
            },
            {
                id: 'apple-pie',
                name: 'Apple Pie',
                description: 'Apple and blend of cinnamon',
                price: 110,
                veg: true,
                category: 'drinks',
                subcategory: 'signature',
            },
            {
                id: 'mango-passion',
                name: 'Mango Passion',
                description: 'A balance mix of mango and passion fruit',
                price: 110,
                veg: true,
                category: 'drinks',
                subcategory: 'signature',
            },
        ],
    },
    {
        id: 'kombucha',
        name: 'Kombucha Tea',
        items: [
            {
                id: 'exotic-peach',
                name: 'Exotic Peach',
                description: 'Exotic peach kombucha tea',
                price: 130,
                veg: true,
                category: 'drinks',
                subcategory: 'kombucha',
            },
            {
                id: 'ginger-lemon',
                name: 'Ginger Lemon',
                description: 'Ginger and lemon kombucha tea',
                price: 130,
                veg: true,
                category: 'drinks',
                subcategory: 'kombucha',
            },
            {
                id: 'pineapple',
                name: 'Pineapple',
                description: 'Pineapple kombucha tea',
                price: 130,
                veg: true,
                category: 'drinks',
                subcategory: 'kombucha',
            },
        ],
    },
    {
        id: 'coffee',
        name: 'Coffee',
        items: [
            {
                id: 'espresso',
                name: 'Espresso',
                description: 'Medium roast espresso',
                price: 75,
                veg: true,
                category: 'coffee',
            },
            {
                id: 'double-espresso',
                name: 'Double Espresso',
                description: 'Double shot medium roast espresso',
                price: 90,
                veg: true,
                category: 'coffee',
            },
            {
                id: 'americano',
                name: 'Americano',
                description: 'Classic americano',
                price: 110,
                veg: true,
                category: 'coffee',
            },
            {
                id: 'latte',
                name: 'Latte',
                description: 'Smooth latte',
                price: 125,
                veg: true,
                category: 'coffee',
            },
            {
                id: 'cappuccino',
                name: 'Cappuccino',
                description: 'Classic cappuccino',
                price: 135,
                veg: true,
                category: 'coffee',
            },
            {
                id: 'hazelnut-cappuccino',
                name: 'Hazelnut Cappuccino',
                description: 'Cappuccino with hazelnut flavor',
                price: 165,
                veg: true,
                category: 'coffee',
            },
            {
                id: 'tiramisu-cappuccino',
                name: 'Tiramisu Cappuccino',
                description: 'Cappuccino with tiramisu flavor',
                price: 165,
                veg: true,
                category: 'coffee',
            },
            {
                id: 'hazelnut-ice-coffee',
                name: 'Hazelnut Ice Coffee',
                description: 'Iced coffee with hazelnut flavor',
                price: 135,
                veg: true,
                category: 'coffee',
            },
            {
                id: 'tiramisu-ice-coffee',
                name: 'Tiramisu Ice Coffee',
                description: 'Iced coffee with tiramisu flavor',
                price: 135,
                veg: true,
                category: 'coffee',
            },
        ],
    },
    {
        id: 'toppings',
        name: 'Extra Toppings',
        items: [
            {
                id: 'cheese-mozzarella',
                name: 'Cheese Mozzarella',
                description: 'Extra mozzarella cheese',
                price: 77,
                veg: true,
                category: 'toppings',
            },
            {
                id: 'cheese-parmesan',
                name: 'Cheese Parmesan',
                description: 'Extra parmesan cheese',
                price: 100,
                veg: true,
                category: 'toppings',
            },
            {
                id: 'veg-topping',
                name: 'Veg Topping',
                description: 'Extra vegetable topping',
                price: 62,
                veg: true,
                category: 'toppings',
            },
            {
                id: 'olive-jalapeno',
                name: 'Olive/Jalapeno',
                description: 'Extra olives or jalapenos',
                price: 25,
                veg: true,
                category: 'toppings',
            },
            {
                id: 'non-veg-topping',
                name: 'Non-Veg Topping',
                description: 'Extra non-veg topping (Chicken/Tuna/Bacon/Chorizo/Pepperoni/Beef/Mutton)',
                price: 110,
                veg: false,
                category: 'toppings',
            },
        ],
    },
];
